update runs

diff --git a/.github/workflows/debian-python-kube.yaml b/.github/workflows/debian-python-kube.yaml
--- a/.github/workflows/debian-python-kube.yaml
+++ b/.github/workflows/debian-python-kube.yaml
@@ -18,29 +18,8 @@ on:
       - containers/shell/**
 
 jobs:
-  verify:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Login to ghcr.io
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Login to dockerhub to avoid rate limits
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Build Debian
-        run: docker build --build-arg PYTHON_VERSION=3.12 -t etma/devcontainer-python:debian-kube -f ./containers/debian-kube.Dockerfile .
   gather:
     runs-on: ubuntu-latest
-    needs: ['verify']
     outputs:
       python-versions: ${{ steps.get-python-versions.outputs.python-versions }}
     steps:
@@ -49,9 +28,56 @@ jobs:
       - name: Get python versions
         id: get-python-versions
         run: |
+          vercomp () {
+              if [[ $1 == $2 ]]
+              then
+                  return 0
+              fi
+              local IFS=.
+              local i ver1=($1) ver2=($2)
+              # fill empty fields in ver1 with zeros
+              for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
+              do
+                  ver1[i]=0
+              done
+              for ((i=0; i<${#ver1[@]}; i++))
+              do
+                  if [[ -z ${ver2[i]} ]]
+              then
+              # fill empty fields in ver2 with zeros
+              ver2[i]=0
+              fi
+              if ((10#${ver1[i]} > 10#${ver2[i]}))
+              then
+                  return 1
+              fi
+              if ((10#${ver1[i]} < 10#${ver2[i]}))
+              then
+                  return 2
+              fi
+              done
+              return 0
+          }
+
+          testvercomp () {
+              vercomp $1 $2
+              case $? in
+              0) op='=';;
+              1) op='>';;
+              2) op='<';;
+              esac
+              if [[ $op != $3 ]]
+              then
+                  echo "FAIL: Expected '$3', Actual '$op', Arg1 '$1', Arg2 '$2'"
+                  return 1
+              else
+                  echo "Pass: '$1 $op $2'"
+                  return 0
+              fi
+          }
           versions=()
           for line in $(docker run continuumio/anaconda3 conda search python | grep -v Name | grep -v '^$' | grep -v 'channels:' | awk '{print $2}' | sort -V | uniq); do
-            if [[ $line == 3* ]]; then
+            if testvercomp $line 3.9 '>'; then
               versions+=($line)
             fi
           done
@@ -59,11 +85,56 @@ jobs:
 
   latest:
     runs-on: ubuntu-latest
-    needs: ['verify', 'gather']
+    needs: ['gather']
     if: github.event_name == 'push'
     permissions:
       packages: write
     steps:
+      - name: Check disk space
+        run: df . -h
+      - name: Free disk space
+        run: |
+          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
+          sudo rm -rf \
+            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
+            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
+            /usr/lib/jvm || true
+          echo "some directories deleted"
+          sudo apt install aptitude -y >/dev/null 2>&1
+          sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+            google-cloud-sdk imagemagick \
+            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+            mercurial apt-transport-https mono-complete libmysqlclient \
+            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+            sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
+            -y -f >/dev/null 2>&1
+          sudo aptitude purge google-cloud-sdk -f -y >/dev/null 2>&1
+          sudo aptitude purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
+          sudo apt purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
+          sudo aptitude purge '~n ^mysql' -f -y >/dev/null 2>&1
+          sudo aptitude purge '~n ^php' -f -y >/dev/null 2>&1
+          sudo aptitude purge '~n ^dotnet' -f -y >/dev/null 2>&1
+          sudo apt-get autoremove -y >/dev/null 2>&1
+          sudo apt-get autoclean -y >/dev/null 2>&1
+          echo "some packages purged"
+      - name: Check disk space
+        run: |
+          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
+          df . -h
+          sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Check working space directory
+        run: du ${GITHUB_WORKSPACE} -h -d 1
+      - name: Get more space
+        run: |
+          df . -h
+          sudo rm -rf ${GITHUB_WORKSPACE}/.git
+          df . -h
+      
       - uses: actions/checkout@v3
 
       - name: Login to ghcr.io
@@ -133,15 +204,60 @@ jobs:
 
   publish:
     runs-on: ubuntu-latest
-    needs: ['verify', 'gather']
+    needs: ['gather']
     if: github.event_name == 'push'
     permissions:
       packages: write
     strategy:
-      max-parallel: 10
+      max-parallel: 3
       matrix:
         python-version: ${{ fromJson(needs.gather.outputs.python-versions) }}
     steps:
+      - name: Check disk space
+        run: df . -h
+      - name: Free disk space
+        run: |
+          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
+          sudo rm -rf \
+            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
+            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
+            /usr/lib/jvm || true
+          echo "some directories deleted"
+          sudo apt install aptitude -y >/dev/null 2>&1
+          sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+            google-cloud-sdk imagemagick \
+            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+            mercurial apt-transport-https mono-complete libmysqlclient \
+            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+            sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
+            -y -f >/dev/null 2>&1
+          sudo aptitude purge google-cloud-sdk -f -y >/dev/null 2>&1
+          sudo aptitude purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
+          sudo apt purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
+          sudo aptitude purge '~n ^mysql' -f -y >/dev/null 2>&1
+          sudo aptitude purge '~n ^php' -f -y >/dev/null 2>&1
+          sudo aptitude purge '~n ^dotnet' -f -y >/dev/null 2>&1
+          sudo apt-get autoremove -y >/dev/null 2>&1
+          sudo apt-get autoclean -y >/dev/null 2>&1
+          echo "some packages purged"
+      - name: Check disk space
+        run: |
+          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
+          df . -h
+          sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Check working space directory
+        run: du ${GITHUB_WORKSPACE} -h -d 1
+      - name: Get more space
+        run: |
+          df . -h
+          sudo rm -rf ${GITHUB_WORKSPACE}/.git
+          df . -h
+      
       - uses: actions/checkout@v3
 
       - name: Login to ghcr.io
